'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { AlertTriangle, ShieldAlert, CheckCircle2 } from 'lucide-react';

export default function RiskDisclaimer() {
    const [isOpen, setIsOpen] = useState(false);
    const [checked, setChecked] = useState(false);

    useEffect(() => {
        const hasAccepted = localStorage.getItem('sentinel_disclaimer_accepted');
        if (!hasAccepted) {
            setIsOpen(true);
        }
    }, []);

    const handleAccept = () => {
        if (checked) {
            localStorage.setItem('sentinel_disclaimer_accepted', 'true');
            setIsOpen(false);
        }
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/80 backdrop-blur-xl">
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        className="glass-panel max-w-lg w-full p-8 rounded-3xl border-red-500/20 relative overflow-hidden"
                    >
                        {/* Background Accent */}
                        <div className="absolute top-0 right-0 w-32 h-32 bg-red-500/10 blur-[60px] pointer-events-none" />

                        <div className="flex items-center gap-4 mb-6 text-red-500">
                            <ShieldAlert size={32} />
                            <h2 className="text-2xl font-black uppercase tracking-tight">Financial Risk Warning</h2>
                        </div>

                        <div className="space-y-4 text-gray-400 font-mono text-xs leading-relaxed overflow-y-auto max-h-[300px] pr-2 custom-scrollbar">
                            <p className="text-white font-bold uppercase">SENTINEL IS AN ALGORITHMIC ANALYSIS TOOL FOR EDUCATIONAL PURPOSES ONLY.</p>

                            <p>1. <span className="text-white">NO FINANCIAL ADVICE:</span> The signals and predictions generated by SENTINEL do not constitute investment advice. Trading cryptocurrencies involves significant risk of loss.</p>

                            <p>2. <span className="text-white">ACCURACY LIMITATIONS:</span> Predictive models are based on historical data. Past performance is never a guarantee of future results. Market conditions can change instantly, rendering indicators obsolete.</p>

                            <p>3. <span className="text-white">USER RESPONSIBILITY:</span> By using this software, you acknowledge that you are solely responsible for your trading decisions. The developers of SENTINEL are not liable for any financial losses incurred.</p>

                            <p>4. <span className="text-white">API USAGE:</span> This bot uses the Binance Public API. External service outages are beyond our control.</p>
                        </div>

                        <div className="mt-8 pt-6 border-t border-white/5 space-y-6">
                            <label className="flex items-start gap-3 cursor-pointer group">
                                <input
                                    type="checkbox"
                                    checked={checked}
                                    onChange={(e) => setChecked(e.target.checked)}
                                    className="mt-1 w-5 h-5 rounded border-white/10 bg-white/5 text-cyber-blue focus:ring-cyber-blue transition-all"
                                />
                                <span className="text-sm text-gray-300 group-hover:text-white transition-colors">
                                    I have read the risk warning and understand that I am trading at my own risk.
                                </span>
                            </label>

                            <button
                                disabled={!checked}
                                onClick={handleAccept}
                                className={`w-full py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${checked
                                        ? 'bg-white text-black hover:bg-gray-200 active:scale-95'
                                        : 'bg-white/5 text-gray-600 cursor-not-allowed'
                                    }`}
                            >
                                <CheckCircle2 size={20} />
                                ENTER V2 CONSOLE
                            </button>
                        </div>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
}
